"""

SOCIAL_AUTH_FACEBOOK_KEY = '411185379075238'
SOCIAL_AUTH_FACEBOOK_SECRET ='476ed5c096a9b0a419eef58c5126b16e' 

http://artandlogic.com/2014/04/tutorial-adding-facebooktwittergoogle-authentication-to-a-django-application/
Django settings for ConnectMe project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from unipath import Path

SOCIAL_AUTH_FACEBOOK_KEY = '411185379075238'
SOCIAL_AUTH_FACEBOOK_SECRET ='476ed5c096a9b0a419eef58c5126b16e' 
SOCIAL_AUTH_FACEBOOK_SCOPE = [
        'email',
        'user_friends',
    ]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_DIR = Path(__file__).parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '31zhlpq!0c--1ko6kjniz%rnvng)jaotfn8xi&qvrq3gky4c1%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'ConnectMe.users',
    'ConnectMe.core',
    'ConnectMe.feeds',
    'background_task',
    'ConnectMe.friendship',
    'django_cron',
    'django_crontab',
    'social.apps.django_app.default',
    'kronos',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.security.SecurityMiddleware',
)
CRON_CLASSES = [
    "ConnectMe.users.cronjob.MyCronJob",
    # ...
]
CRONJOBS = [
    ('*/1 * * * *', 'ConnectMe.users.cronjob1.my_scheduled_job')
]


ROOT_URLCONF = 'ConnectMe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.core.context_processors.debug',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'django.core.context_processors.static',
                'django.core.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'ConnectMe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
PROJECT_DIR = os.path.dirname(__file__)

STATICFILES_DIRS = (os.path.join(PROJECT_DIR, 'static'),)
MEDIA_ROOT = os.path.join(PROJECT_DIR,'..','media')
MEDIA_URL = '/media/'


LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'

ALLOWED_SIGNUP_DOMAINS = ['*']

FILE_UPLOAD_TEMP_DIR = '/tmp/'
FILE_UPLOAD_PERMISSIONS = 0644

#EMAIL_BACKEND = "django.core.mail.backends.smtp.Console"
# Optional SMTP authentication informati
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'cn.subject@gmail.com'
EMAIL_HOST_PASSWORD = 'sg19892808'
EMAIL_PORT = 587
SITE_HOST = '192.168.1.183:8000'
DEFAULT_FROM_EMAIL='cn.subject@gmail.com'
#SESSION_COOKIE_AGE = 360
AUTHENTICATION_BACKENDS = (
   'social.backends.facebook.FacebookOAuth2',
   'social.backends.google.GoogleOAuth2',
   'social.backends.twitter.TwitterOAuth',
   'django.contrib.auth.backends.ModelBackend',
)